### ISSUE TITLE
Don't use RX/TX pins for LED/Button

### ISSUE THREAD

**Issue by bgomberg** [roboshield/roboshield#7]
We should see if we could avoid using these pins all-together. We should at least not use them for the button / LED as this will mess with people who want to use the serial monitor.

**Comment by jsseng** [comment]
Isn't the serial monitor a 1-way output?  Can we a leave the LED on the TX and the RX will be prevent serial input?

**Comment by jsseng** [comment]
The button could also go on the battery analog input.

**Comment by bgomberg** [comment]
Somebody might want to type stuff into the serial monitor for debugging purposes.

**Comment by bgomberg** [comment]
Move the BTN to the LCD_RS pin.
